# Generated by Django 2.2.5 on 2020-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaugacampuriuseri',
            name='portofolio_site',
        ),
        migrations.AddField(
            model_name='adaugacampuriuseri',
            name='profile_site',
            field=models.URLField(blank=True),
        ),
    ]
