# Generated by Django 3.0.5 on 2020-04-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userourmodel',
            old_name='portofolio_pic',
            new_name='profile_pic',
        ),
    ]
